@echo off
chcp 65001 >nul
setlocal enabledelayedexpansion

echo ==========================================
echo   Membuat struktur folder dan file
echo   Website Ujian Online - Next.js + Prisma
echo ==========================================
echo.

REM ============ MEMBUAT FOLDER ============
if not exist "prisma" mkdir "prisma"
if not exist "prisma\migrations" mkdir "prisma\migrations"
if not exist "src" mkdir "src"
if not exist "src\app" mkdir "src\app"
if not exist "src\app\(auth)\login" mkdir "src\app\(auth)\login"
if not exist "src\app\(auth)\register" mkdir "src\app\(auth)\register"
if not exist "src\app\(admin)\dashboard" mkdir "src\app\(admin)\dashboard"
if not exist "src\app\(admin)\ujian\create" mkdir "src\app\(admin)\ujian\create"
if not exist "src\app\(admin)\ujian\[id]\edit" mkdir "src\app\(admin)\ujian\[id]\edit"
if not exist "src\app\(admin)\ujian\[id]\soal" mkdir "src\app\(admin)\ujian\[id]\soal"
if not exist "src\app\(admin)\ujian\[id]\hasil" mkdir "src\app\(admin)\ujian\[id]\hasil"
if not exist "src\app\(admin)\peserta\[id]" mkdir "src\app\(admin)\peserta\[id]"
if not exist "src\app\(admin)\kartu-ujian" mkdir "src\app\(admin)\kartu-ujian"
if not exist "src\app\(peserta)\ujian\[id]" mkdir "src\app\(peserta)\ujian\[id]"
if not exist "src\app\(peserta)\hasil\[id]" mkdir "src\app\(peserta)\hasil\[id]"
if not exist "src\app\api\auth\[...nextauth]" mkdir "src\app\api\auth\[...nextauth]"
if not exist "src\app\api\auth\register" mkdir "src\app\api\auth\register"
if not exist "src\app\api\ujian\[id]" mkdir "src\app\api\ujian\[id]"
if not exist "src\app\api\soal\[id]" mkdir "src\app\api\soal\[id]"
if not exist "src\app\api\hasil-ujian\[id]\submit" mkdir "src\app\api\hasil-ujian\[id]\submit"
if not exist "src\app\api\jawaban" mkdir "src\app\api\jawaban"
if not exist "src\app\api\pelanggaran" mkdir "src\app\api\pelanggaran"
if not exist "src\app\api\kartu-ujian\generate-password" mkdir "src\app\api\kartu-ujian\generate-password"
if not exist "src\components\ui" mkdir "src\components\ui"
if not exist "src\components\ujian" mkdir "src\components\ujian"
if not exist "src\components\admin" mkdir "src\components\admin"
if not exist "src\components\layout" mkdir "src\components\layout"
if not exist "src\hooks" mkdir "src\hooks"
if not exist "src\lib\validations" mkdir "src\lib\validations"
if not exist "src\types" mkdir "src\types"
if not exist "public" mkdir "public"

REM ============ MEMBUAT FILE KOSONG ============
if not exist "prisma\schema.prisma" type nul > "prisma\schema.prisma"
if not exist "prisma\seed.ts" type nul > "prisma\seed.ts"
if not exist "prisma.config.ts" type nul > "prisma.config.ts"
if not exist "src\app\(auth)\login\page.tsx" type nul > "src\app\(auth)\login\page.tsx"
if not exist "src\app\(auth)\register\page.tsx" type nul > "src\app\(auth)\register\page.tsx"
if not exist "src\app\(admin)\layout.tsx" type nul > "src\app\(admin)\layout.tsx"
if not exist "src\app\(admin)\dashboard\page.tsx" type nul > "src\app\(admin)\dashboard\page.tsx"
if not exist "src\app\(admin)\ujian\page.tsx" type nul > "src\app\(admin)\ujian\page.tsx"
if not exist "src\app\(admin)\ujian\create\page.tsx" type nul > "src\app\(admin)\ujian\create\page.tsx"
if not exist "src\app\(admin)\ujian\[id]\edit\page.tsx" type nul > "src\app\(admin)\ujian\[id]\edit\page.tsx"
if not exist "src\app\(admin)\ujian\[id]\soal\page.tsx" type nul > "src\app\(admin)\ujian\[id]\soal\page.tsx"
if not exist "src\app\(admin)\ujian\[id]\hasil\page.tsx" type nul > "src\app\(admin)\ujian\[id]\hasil\page.tsx"
if not exist "src\app\(admin)\peserta\page.tsx" type nul > "src\app\(admin)\peserta\page.tsx"
if not exist "src\app\(admin)\peserta\[id]\page.tsx" type nul > "src\app\(admin)\peserta\[id]\page.tsx"
if not exist "src\app\(admin)\kartu-ujian\page.tsx" type nul > "src\app\(admin)\kartu-ujian\page.tsx"
if not exist "src\app\(peserta)\layout.tsx" type nul > "src\app\(peserta)\layout.tsx"
if not exist "src\app\(peserta)\page.tsx" type nul > "src\app\(peserta)\page.tsx"
if not exist "src\app\(peserta)\ujian\[id]\page.tsx" type nul > "src\app\(peserta)\ujian\[id]\page.tsx"
if not exist "src\app\(peserta)\hasil\[id]\page.tsx" type nul > "src\app\(peserta)\hasil\[id]\page.tsx"
if not exist "src\app\api\auth\[...nextauth]\route.ts" type nul > "src\app\api\auth\[...nextauth]\route.ts"
if not exist "src\app\api\auth\register\route.ts" type nul > "src\app\api\auth\register\route.ts"
if not exist "src\app\api\ujian\route.ts" type nul > "src\app\api\ujian\route.ts"
if not exist "src\app\api\ujian\[id]\route.ts" type nul > "src\app\api\ujian\[id]\route.ts"
if not exist "src\app\api\soal\route.ts" type nul > "src\app\api\soal\route.ts"
if not exist "src\app\api\soal\[id]\route.ts" type nul > "src\app\api\soal\[id]\route.ts"
if not exist "src\app\api\hasil-ujian\route.ts" type nul > "src\app\api\hasil-ujian\route.ts"
if not exist "src\app\api\hasil-ujian\[id]\route.ts" type nul > "src\app\api\hasil-ujian\[id]\route.ts"
if not exist "src\app\api\hasil-ujian\[id]\submit\route.ts" type nul > "src\app\api\hasil-ujian\[id]\submit\route.ts"
if not exist "src\app\api\jawaban\route.ts" type nul > "src\app\api\jawaban\route.ts"
if not exist "src\app\api\pelanggaran\route.ts" type nul > "src\app\api\pelanggaran\route.ts"
if not exist "src\app\api\kartu-ujian\route.ts" type nul > "src\app\api\kartu-ujian\route.ts"
if not exist "src\app\api\kartu-ujian\generate-password\route.ts" type nul > "src\app\api\kartu-ujian\generate-password\route.ts"
if not exist "src\app\layout.tsx" type nul > "src\app\layout.tsx"
if not exist "src\app\page.tsx" type nul > "src\app\page.tsx"
if not exist "src\app\globals.css" type nul > "src\app\globals.css"
if not exist "src\components\ui\Button.tsx" type nul > "src\components\ui\Button.tsx"
if not exist "src\components\ui\Input.tsx" type nul > "src\components\ui\Input.tsx"
if not exist "src\components\ui\Card.tsx" type nul > "src\components\ui\Card.tsx"
if not exist "src\components\ui\Modal.tsx" type nul > "src\components\ui\Modal.tsx"
if not exist "src\components\ujian\Timer.tsx" type nul > "src\components\ujian\Timer.tsx"
if not exist "src\components\ujian\SoalCard.tsx" type nul > "src\components\ujian\SoalCard.tsx"
if not exist "src\components\ujian\NavigasiSoal.tsx" type nul > "src\components\ujian\NavigasiSoal.tsx"
if not exist "src\components\ujian\PeringatanModal.tsx" type nul > "src\components\ujian\PeringatanModal.tsx"
if not exist "src\components\ujian\WatermarkIdentitas.tsx" type nul > "src\components\ujian\WatermarkIdentitas.tsx"
if not exist "src\components\admin\FormUjian.tsx" type nul > "src\components\admin\FormUjian.tsx"
if not exist "src\components\admin\FormSoal.tsx" type nul > "src\components\admin\FormSoal.tsx"
if not exist "src\components\admin\TabelHasil.tsx" type nul > "src\components\admin\TabelHasil.tsx"
if not exist "src\components\admin\LogPelanggaranTable.tsx" type nul > "src\components\admin\LogPelanggaranTable.tsx"
if not exist "src\components\admin\KartuUjianPreview.tsx" type nul > "src\components\admin\KartuUjianPreview.tsx"
if not exist "src\components\layout\Navbar.tsx" type nul > "src\components\layout\Navbar.tsx"
if not exist "src\components\layout\SidebarAdmin.tsx" type nul > "src\components\layout\SidebarAdmin.tsx"
if not exist "src\components\layout\Footer.tsx" type nul > "src\components\layout\Footer.tsx"
if not exist "src\hooks\useAntiCheat.ts" type nul > "src\hooks\useAntiCheat.ts"
if not exist "src\hooks\useTimer.ts" type nul > "src\hooks\useTimer.ts"
if not exist "src\hooks\useAutoSave.ts" type nul > "src\hooks\useAutoSave.ts"
if not exist "src\lib\prisma.ts" type nul > "src\lib\prisma.ts"
if not exist "src\lib\auth.ts" type nul > "src\lib\auth.ts"
if not exist "src\lib\utils.ts" type nul > "src\lib\utils.ts"
if not exist "src\lib\validations\auth.schema.ts" type nul > "src\lib\validations\auth.schema.ts"
if not exist "src\lib\validations\ujian.schema.ts" type nul > "src\lib\validations\ujian.schema.ts"
if not exist "src\lib\validations\soal.schema.ts" type nul > "src\lib\validations\soal.schema.ts"
if not exist "src\lib\validations\jawaban.schema.ts" type nul > "src\lib\validations\jawaban.schema.ts"
if not exist "src\types\next-auth.d.ts" type nul > "src\types\next-auth.d.ts"
if not exist "src\types\index.ts" type nul > "src\types\index.ts"
if not exist "src\middleware.ts" type nul > "src\middleware.ts"

echo.
echo ==========================================
echo   Selesai! Semua folder dan file berhasil dibuat.
echo ==========================================
pause